#pragma once
#include "src.h"
#include "syn.h"
#include "parser.h" // generated by bison

static inline
void get_line_column(voba_str_t* c, uint32_t pos, uint32_t* line, uint32_t *col)
{
    *line = 1;
    *col = 0;
    for(uint32_t i = 0; i < pos && i < c->len; ++i){
        if(c->data[i] == '\n'){
            ++ *line;
            *col = 0;
        }else{
            ++ *col;
        }
    }
}
inline
static void syntax_loc(voba_value_t a , YYLTYPE* b)
{
    SYNTAX(a)->start_pos = b->start_pos;
    SYNTAX(a)->end_pos = b->end_pos;
}


